#!/usr/bin/env bash
# Export Instagram cookies from a local browser and upload to the bot VPS.
#
# Required in .env (repo root, gitignored):
#   DEPLOY_SSH_HOST=178.x.x.x
#   DEPLOY_SSH_KEY=/Users/you/.ssh/personal
#   IG_COOKIES_REMOTE_PATH=/etc/fatctrlbot/instagram_cookies.txt
#
# Optional:
#   DEPLOY_SSH_USER=root
#   IG_COOKIES_BROWSER=chrome   # chrome | safari | firefox | brave | edge
#   YTDLP=yt-dlp                # or: python3 -m yt_dlp
#   IG_COOKIES_TEST_URL=https://www.instagram.com/reel/...
#
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="${ENV_FILE:-$ROOT/.env}"

if [[ -f "$ENV_FILE" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
fi

require() {
  local name="$1"
  if [[ -z "${!name:-}" ]]; then
    echo "Missing $name — set it in $ENV_FILE" >&2
    exit 1
  fi
}

require DEPLOY_SSH_HOST
require DEPLOY_SSH_KEY
require IG_COOKIES_REMOTE_PATH

DEPLOY_SSH_USER="${DEPLOY_SSH_USER:-root}"
IG_COOKIES_BROWSER="${IG_COOKIES_BROWSER:-chrome}"
IG_COOKIES_TEST_URL="${IG_COOKIES_TEST_URL:-https://www.instagram.com/reel/DcJGLCxMVgr/}"

if [[ -n "${YTDLP:-}" ]]; then
  YTDLP_CMD=($YTDLP)
elif command -v yt-dlp >/dev/null 2>&1; then
  YTDLP_CMD=(yt-dlp)
elif python3 -m yt_dlp --version >/dev/null 2>&1; then
  YTDLP_CMD=(python3 -m yt_dlp)
else
  echo "yt-dlp not found — install it or set YTDLP in .env (e.g. python3 -m yt_dlp)" >&2
  exit 1
fi

SSH=(ssh -i "$DEPLOY_SSH_KEY" -o ConnectTimeout=15 "${DEPLOY_SSH_USER}@${DEPLOY_SSH_HOST}")
SCP=(scp -i "$DEPLOY_SSH_KEY" -o ConnectTimeout=15)

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

RAW="$TMP_DIR/all_cookies.txt"
FILTERED="$TMP_DIR/instagram_cookies.txt"

echo "→ Export cookies from $IG_COOKIES_BROWSER …"
"${YTDLP_CMD[@]}" --cookies-from-browser "$IG_COOKIES_BROWSER" \
  --cookies "$RAW" \
  --print title \
  --no-download \
  "$IG_COOKIES_TEST_URL" >/dev/null

if ! grep -q '\.instagram\.com' "$RAW"; then
  echo "No .instagram.com cookies — log into Instagram in $IG_COOKIES_BROWSER first." >&2
  exit 1
fi

{
  echo '# Netscape HTTP Cookie File'
  echo '# This file is generated by yt-dlp.  Do not edit.'
  echo
  grep '\.instagram\.com' "$RAW"
} > "$FILTERED"

if ! grep -q $'\tsessionid\t' "$FILTERED"; then
  echo "Warning: sessionid missing — export may not work on the server." >&2
fi

echo "→ Upload to ${DEPLOY_SSH_USER}@${DEPLOY_SSH_HOST}:${IG_COOKIES_REMOTE_PATH} …"
"${SCP[@]}" "$FILTERED" "${DEPLOY_SSH_USER}@${DEPLOY_SSH_HOST}:${IG_COOKIES_REMOTE_PATH}"
"${SSH[@]}" "chmod 600 '${IG_COOKIES_REMOTE_PATH}'"

echo "→ Test on server …"
TITLE=$("${SSH[@]}" "yt-dlp --cookies '${IG_COOKIES_REMOTE_PATH}' --print title --no-download '${IG_COOKIES_TEST_URL}' 2>/dev/null" || true)
if [[ -n "$TITLE" ]]; then
  echo "OK: $TITLE"
else
  echo "Upload done, but server test failed — check yt-dlp and cookies on VPS." >&2
  exit 1
fi
